# Avoid bots branches
branches:
  only:
    - /[a-zA-Z_]*/

# Exit build if not necessary
before_install:
  # run only if current implementation is modified
  - .ci/has_to_run.sh || travis_terminate 0

  # Load docker cache
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

# Use docker to containerize frameworks
services: docker

# Declare cache folders
cache:
  directories:
    - $HOME/docker

# Cache docker images (only tagged ones)
before_cache:
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

# This tool is written in crystal
language: crystal

# One build per framework
# ! This list list has to be updated manually !
env:
  matrix:
    - FRAMEWORK=agoo
    - FRAMEWORK=agoo-c

# Lint yaml files in a specific jobs
jobs:
  include:
    - stage: lint
      script: bash .ci/lint.sh
      env: FRAMEWORK=rails

script:
  - shards build
  - bin/neph -v
  - bin/neph ${FRAMEWORK} --mode=CI --seq
  - crystal spec

notifications:
  email: false
